{
  blog {
    title,
  	text,
    author {
      _id,
      firstName
      lastName
    },
		image,
    shortText,
    tag,
    category{
      _id
      title
    }
    CommentBlog{
      comment
      show
      openToComment
      createdAt
      user{
        _id
        firstName
        lastName
      }
      parent{
        user{
          _id
				firstName
        lastName
        }
      comment
      show
      openToComment
      createdAt
      }
    }
  }
}